import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  
  title: "Pascal Niri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <Head>
          <title>Pascal Niri</title>
          <Link rel="icon" href="/pascal.jpg" />
      </Head>
      <body className={inter.className}>
        <div className="bg-[#11071F] m-auto min-h-[100vh]">
          <Navbar />
          {children}
          </div>
      </body>
    </html>
  );
}
